### ISSUE TITLE
Unable to handle List<Link>

### ISSUE THREAD

**Issue by asgeirn** [FINTLabs/fint-graphql#4]
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'graphQLServletRegistrationBean' defined in class path resource [com/oembedler/moon/graphql/boot/GraphQLWebAutoConfiguration.class]: Unsatisfied dependency expressed through method 'graphQLServletRegistrationBean' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'graphQLHttpServlet' defined in class path resource [com/oembedler/moon/graphql/boot/GraphQLWebAutoConfiguration.class]: Unsatisfied dependency expressed through method 'graphQLHttpServlet' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'invocationInputFactory' defined in class path resource [com/oembedler/moon/graphql/boot/GraphQLWebAutoConfiguration.class]: Unsatisfied dependency expressed through method 'invocationInputFactory' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'graphQLSchemaProvider' defined in class path resource [com/oembedler/moon/graphql/boot/GraphQLWebAutoConfiguration.class]: Unsatisfied dependency expressed through method 'graphQLSchemaProvider' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'graphQLSchema' defined in class path resource [com/oembedler/moon/graphql/boot/GraphQLJavaToolsAutoConfiguration.class]: Unsatisfied dependency expressed through method 'graphQLSchema' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'schemaParser' defined in class path resource [com/oembedler/moon/graphql/boot/GraphQLJavaToolsAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.coxautodev.graphql.tools.SchemaParser]: Factory method 'schemaParser' threw exception; nested exception is com.coxautodev.graphql.tools.TypeClassMatcher$RawClassRequiredForGraphQLMappingException: Type java.util.List<no.fint.model.resource.Link> cannot be mapped to a GraphQL type!  Since GraphQL-Java deals with erased types at runtime, only non-parameterized classes can represent a GraphQL type.  This allows for reverse-lookup by java class in interfaces and union types.
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:732) ~[spring-beans-5.0.9.RELEASE.jar:5.0.9.RELEASE]

**Comment by asgeirn** [comment]
What I cannot understand is why this error is thrown now, and not before?

**Comment by jarlehansen** [comment]
This is strange, I have updated the graphql versions and I am getting another issue now. Looking into it, we probably have multiple issues here.

**Comment by asgeirn** [comment]
The issues now are related to relations having conflicting types in GraphQL schema compared to the resource model classes.

In the resource model classes, relations are expressed as `List<Link>`, but in the GraphQL generated schema they are expressed using the target type.

It appears possible to get past this by removing relations in the generated schema, but this defeats the purpose.

So the solution is probably to use the plain classes instead of resource classes.  This has impacts for the generated resolver classes, but should be possible to overcome.

**Comment by jarlehansen** [comment]
Yes, it is because the naming and return types (where it is Link).
Will see if we have any options here, or if the only solution is to not use the resource class as you said.

**Comment by jarlehansen** [comment]
One problem here can be fixed by adding the correct named methods to the resolver. For instance, in `ansvar.graphqls` there is a field called "overordnet". In the `AnsvarResolver` there should be a method like this  
```
public AnsvarResource getOverordnet(AnsvarResource ansvar) {
   return ansvarService.getAnsvarResource(Links.get(ansvar, "overordnet"));
}
```

I have tried to fix this in all the resolvers, the next problem I am getting now is that it is unable to find a resolver for `gyldyighetsperiode`:

```
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.coxautodev.graphql.tools.SchemaParser]: Factory method 'schemaParser' threw exception; nested exception is com.coxautodev.graphql.tools.FieldResolverError: No method or field found as defined in schema <unknown>:329 with any of the following signatures (with or without one of [interface graphql.schema.DataFetchingEnvironment] as the last argument), in priority order:

  java.util.List.gyldighetsperiode()
  java.util.List.getGyldighetsperiode()
  java.util.List.gyldighetsperiode
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185) ~[spring-beans-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:583) ~[spring-beans-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	... 93 common frames omitted
Caused by: com.coxautodev.graphql.tools.FieldResolverError: No method or field found as defined in schema <unknown>:329 with any of the following signatures (with or without one of [interface graphql.schema.DataFetchingEnvironment] as the last argument), in priority order:

  java.util.List.gyldighetsperiode()
  java.util.List.getGyldighetsperiode()
  java.util.List.gyldighetsperiode
```

**Comment by asgeirn** [comment]
Aha!  I've updated the resolvers to use relation names instead of target types, and now I get a different kind of error:

```
Caused by: com.coxautodev.graphql.tools.FieldResolverError: No method or field found as defined in schema <unknown>:658 with any of the following signatures (with or without one of [interface graphql.schema.DataFetchingEnvironment] as the last argument), in priority order:

  no.fint.graphql.model.administrasjon.fravar.FravarResolver.dokumentert(no.fint.model.resource.administrasjon.personal.FravarResource)
  no.fint.graphql.model.administrasjon.fravar.FravarResolver.isDokumentert(no.fint.model.resource.administrasjon.personal.FravarResource)
  no.fint.graphql.model.administrasjon.fravar.FravarResolver.getDokumentert(no.fint.model.resource.administrasjon.personal.FravarResource)
  no.fint.graphql.model.administrasjon.fravar.FravarResolver.dokumentert
  no.fint.model.resource.administrasjon.personal.FravarResource.dokumentert()
  no.fint.model.resource.administrasjon.personal.FravarResource.isDokumentert()
  no.fint.model.resource.administrasjon.personal.FravarResource.getDokumentert()
  no.fint.model.resource.administrasjon.personal.FravarResource.dokumentert
```

This one is going to be a lot harder to squish, as it's due to the model having two classes called `Fravar`, and GraphQL schema do not support namespaces.

**Comment by jarlehansen** [comment]
@asgeirn I am trying some different strategies, but I am getting stuck with this error message. Do you have any idea what triggers this error? I am not sure why its looking into "gyldighetsperiode" in List.  
```
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'graphQLSchemaProvider' defined in class path resource [com/oembedler/moon/graphql/boot/GraphQLWebAutoConfiguration.class]: Unsatisfied dependency expressed through method 'graphQLSchemaProvider' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'graphQLSchema' defined in class path resource [com/oembedler/moon/graphql/boot/GraphQLJavaToolsAutoConfiguration.class]: Unsatisfied dependency expressed through method 'graphQLSchema' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'schemaParser' defined in class path resource [com/oembedler/moon/graphql/boot/GraphQLJavaToolsAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.coxautodev.graphql.tools.SchemaParser]: Factory method 'schemaParser' threw exception; nested exception is com.coxautodev.graphql.tools.FieldResolverError: No method or field found as defined in schema <unknown>:157 with any of the following signatures (with or without one of [interface graphql.schema.DataFetchingEnvironment] as the last argument), in priority order:

  java.util.List.gyldighetsperiode()
  java.util.List.getGyldighetsperiode()
  java.util.List.gyldighetsperiode
```

**Comment by asgeirn** [comment]
No obvious reason, but both `administrasjon/fravarstype.graphqls` and `utdanning/fravarstype.graphqls` have a field of this name. Perhaps it's a side effect of this name collision?

Discussing with @fsjovatsen today, the first strategy to try is to add functionality in /FINTLabs/fint-graphql-cli to exclude certain classes from the generated schema and code.

**Comment by asgeirn** [comment]
I've added functionality in fint-graphql-cli to exclude classes, and when excluding `Fravar` it starts up correctly!

**Comment by jarlehansen** [comment]
Nice!

I think another addition is that more resources should be added to the `root.graphqls`.
Looks like the classes are generated, but are not in the schema.

Also, I see that there are quite a few deprecated classes, such as `MedlemskapResource`.
Should they be replaced with a different class?

**Comment by asgeirn** [comment]
Yeah, `root.graphqls` is written by hand for now, it should probably be generated as well.

But the generator needs help in finding classes that are interesting starting points for queries.

`Medlemskap` is deprecated in the information model.
